name: Build Windows Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: ./build
      run: cmake ..

    - name: Build with CMake
      working-directory: ./build
      run: cmake --build . --config Release

    - name: Copy necessary files
      run: |
        mkdir dist
        copy build\Release\*.exe dist\ || copy build\*.exe dist\
        copy config.ini dist\ || echo "config.ini not found, skipping"

    - name: Create ZIP archive
      run: |
        Compress-Archive -Path dist\* -DestinationPath app.zip

    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app.zip
        asset_name: windows-app.zip
        asset_content_type: application/zip
